apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - ../../../Base/microservice.worker.chatbot.settings.csharp/

namePrefix: dev-
nameSuffix: ""

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: microservice-worker-chatbot-settings-csharp-deployment
