
namespace: development

resources:
  - ../../../Base/microservice.worker.chatbot.settings.csharp/

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: microservice-worker-chatbot-settings-csharp-deployment
