apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../../Base/microservice.worker.chatbot.settings.csharp

patchesStrategicMerge:
  - patch-deployment.yaml
