
namespace: production
resources:
  - ../../../Base/microservice.api.chatbot.settings.csharp/

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: microservice-api-chatbot-settings-csharp-deployment
