apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production
resources:
  - ../../../Base/microservice.api.chatbot.settings.csharp/

namePrefix: prod-
nameSuffix: ""

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: microservice-api-chatbot-settings-csharp-deployment
