apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://dev.azure.com/solvexdominicana/Coosajo/_git/Coosajo-IaC
    targetRevision: HEAD
    path: Overlays/dev
    directory:
      recurse: true
      
  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
