apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://dev.azure.com/solvexdominicana/Coosajo/_git/Coosajo-IaC
    targetRevision: HEAD
    path: Overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
