apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../../Base/microservice.chatbot.puppet.csharp/

patchesStrategicMerge:
  - patch-deployment.yaml
