
namespace: production
resources:
  - ../../../Base/microservice.chatbot.puppet.csharp/

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: microservice-chatbot-puppet-csharp-deployment
