apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic-backoffice-react-deployment
  labels:
    project: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolithic-backoffice-react-deployment
  template:
    metadata:
      labels:
        app: monolithic-backoffice-react-deployment
    spec:
      containers:
        - name: monolithic-backoffice-react-deployment
          image: sxbotbuildercontainerregistry.azurecr.io/monolithic.backoffice.react:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "128Mi"
              cpu: "64m"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "echo 'Shutting down...' && sleep 5"]
      imagePullSecrets:
        - name: imagepull
      terminationGracePeriodSeconds: 30
