workerVersion: v1
kind: Service
metadata:
  name: monolithic-backoffice-react-service
  labels:
    project: chatbot
spec:
  selector:
    app:  monolithic-backoffice-react-deployment
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80