apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - ../../../Base/monolithic.backoffice.react/

namePrefix: dev-
nameSuffix: ""

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: monolithic-backoffice-react-deployment
