

namespace: development

resources:
  - ../../../Base/monolithic.backoffice.react/

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: monolithic-backoffice-react-deployment
