
namespace: development

resources:
- ../../../Base/microservice.chatbot.puppet.csharp/

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: microservice.chatbot.puppet.csharp-deployment

images:
- name: microservice.chatbot.puppet.csharp
  newName: sxbotbuildercontainerregistry.azurecr.io/microservice.chatbot.puppet.csharp
  newTag: "20250512.20"
