apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-chatbot-puppet-csharp-deployment
  project: chatbot
spec:
  template:
    spec:
      containers:
      - name:  microservice-chatbot-puppet-csharp-deployment