apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic-backoffice-react-deployment
  project: chatbot
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name:  monolithic-backoffice-react-deployment