apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-worker-chatbot-settings-csharp-deployment
  labels:
    project: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-worker-chatbot-settings-csharp-deployment
  template:
    metadata:
      labels:
        app: microservice-worker-chatbot-settings-csharp-deployment
    spec:
      containers:
        - name: microservice-worker-chatbot-settings-csharp-deployment
          image: sxbotbuildercontainerregistry.azurecr.io/microservice.worker.chatbot.settings.csharp:latest
          envFrom:
            - configMapRef:
                name: worker-settings-config
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "128Mi"
              cpu: "64m"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "echo 'Shutting down...' && sleep 5"]
      imagePullSecrets:
        - name: imagepull
      terminationGracePeriodSeconds: 30
