apiVersion: v1
kind: Service
metadata:
  name: microservice-worker-chatbot-settings-csharp-service
  labels:
    project: chatbot
spec:
  selector:
    app:  microservice-worker-chatbot-settings-csharp-deployment
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80